### ISSUE TITLE
Directory

### ISSUE THREAD

**Issue by ptofoli** [malfunct/SyncCollection#1]
Hi,
I really liked this project, it was all I needed. But sorry for my ignorance, how do I select a specific directory for the files?

**Comment by malfunct** [comment]
The files always get downloaded to a sub directory of the working directory that has the same name as the collection. There is nothing currently in the code to support an alternate location but I think it would be easy for someone to add the functionality if they wanted.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
