### ISSUE TITLE
Error while downloading on apple_ii_library_4am

### ISSUE THREAD

**Issue by 8ree** [malfunct/SyncCollection#10]
Using 1.11 version of synccollection I get a "Error while downloading An exception occurred during a WebClient request." on 8 files.
![Sync](https://github.com/malfunct/SyncCollection/assets/141555483/8584ac4c-d15a-4a64-a439-12bb0cdbaaa4)

I get the same error using v1.10

[fileList.txt](https://github.com/malfunct/SyncCollection/files/12269173/fileList.txt)

**Comment by malfunct** [comment]
I see these as well and they seem to be an issue on the archive.

To test you can copy the item name, the last part of the URL, and search for it on the archive website. Click the "all files" download link on the page and it will also error out with a network error. If the browser can't download the file the sync tool has no hope.

**Comment by malfunct** [comment]
One other thought I have is if you see these errors and multiple runs of the tool don't clear them, try again in a few days and the archive may have fixed the issue, for instance wordattack in your image above seems to be operating correctly again.

My behavior is to sync a collection a couple times and then in a week repeat. There is no error recovery built into the tool which made it easy to program, the idea being that it was easy to re-run and none of the successfully downloaded files would be downloaded again.

**Comment by 8ree** [comment]
I wondered as much.
thanks for confirming
