### ISSUE TITLE
Download quits when encountering 404 error

### ISSUE THREAD

**Issue by imperialone** [malfunct/SyncCollection#3]
Hello, I'm trying to download a large collection consisting of 25,000 files.  Your script seems to work with downloading, but it quits when it encounters the following:
--
Downloading remix-nin-com-collection/remix-nin-com-audio-00267.zip
Downloading from https://archive.org/compress/remix-nin-com-audio-00267
Error while downloading The remote server returned an error: (404) Not Found.
--

**Comment by malfunct** [comment]
The code is not stopping when it gets a 404 error, it has a hard coded limit to only attempt to download the first 2000 items in the collection. The error reporting you are seeing is just telling you that the file failed to download and then the code goes onto the next item available.

I did this to limit how much stress is put on the archive.org search engine by this tool. You can change the limit by changing the value of the Rows constant.

Long term the real fix is to have pagination so the tool can grab 2000 files at a time until the collection is fully downloaded but I doubt whether I'll get around to implementing that.

**Comment by imperialone** [comment]
Thanks for responding.  What I'm experiencing is different from what you describe.  The code is not able to get past the 404 error and continue downloading.  It has downloaded 222 files, but is not able to download the next one (the one I pasted in the original post).  When I try re-running SyncCollection.exe, it starts from the point it previously failed, but fails again because of the 404 error.

**Comment by malfunct** [comment]
Let me try this locally and see if I can isolate the behavior. The code "should" catch the 404 error and move on. I'll have to see what is going on.

**Comment by malfunct** [comment]
I saw the 404 failure on my machine but the code correctly went on to the next file in the collection and did not stop. Any chance you could run this under the debugger and find the line it is actually failing on? It shouldn't be the web error because the code catches web exceptions and skip over them.

**Comment by malfunct** [comment]
My other thought is to ask you where you got your build? Maybe it is out of date and doesn't have the skip logic in it that the current code has. If you are using a build from somewhere else I'd recommend downloading the latest code and building it.

**Comment by malfunct** [comment]
I just created a new release that is the same code I am using on my pc to download. I just retested and it properly skips files that cause 404 errors and goes on to the next file so hopefully if you use that release it works?

**Comment by imperialone** [comment]
Hello, thank you for looking into this!  It could very well be that I have an older version as I did not do the build myself.  I downloaded the binary from somewhere (can't remember where now), as I'm not a programmer and don't know off-hand how to do a build.  Do I need Visual Studio?

**Comment by malfunct** [comment]
You would use visual studio to build the code. I don't think you need to as you can get the latest version from github now. I added it as the v1.0 release.

**Comment by malfunct** [comment]
https://github.com/malfunct/SyncCollection/releases

to find the available releases.

**Comment by imperialone** [comment]
Thank you so much! I've confirmed v1.0 skips the problem file and continues downloading the rest of the collection.  Thank you again!

**Comment by malfunct** [comment]
Glad that this is fixed.
