### ISSUE TITLE
Select filetype?

### ISSUE THREAD

**Issue by NULUSIOS** [malfunct/SyncCollection#4]
Fantastic tool! And weirdly enough I also used it to download Apple II WOZ files. :D
I wonder if the tool can be extended to not fully sync a collection and just download a specific file extension (in our case .woz).
Is it possible?

**Comment by malfunct** [comment]
Not easily if at all. Right now I get a list of item names which is easily put in a URL for downloading the zip of all contents for the item. To get specific files there would need to be a additional query for finding the individual files in the item and then figure out how to turn that list into URLs for downloading the files.

It is not work I plan to do as the utility does what I want but the code is available so feel free to make changes and send a pull request.

**Comment by NULUSIOS** [comment]
Thanks for the reply. I did what I could with the program as is.
A bit more work but ok.
