### ISSUE TITLE
Modern .NET support

### ISSUE THREAD

**Issue by mnadareski** [malfunct/SyncCollection#8]
.NET 4.5.2 is very old at this point. Migrating this to a newer (or set of newer) .NET versions would be nice. If .NET Framework is needed, 4.8 is a good choice. Otherwise, both .NET Core 3.1 and .NET 6.0 are LTS versions that can be updated to.

**Comment by malfunct** [comment]
Feel free to submit a pull request with the change and I will evaluate it. I really just recommend using the archive.org python library at this point instead of this utility though.

**Comment by mnadareski** [comment]
Much appreciated. I like having the .NET version of these things instead of Python for personal reasons.

**Comment by malfunct** [comment]
I merged your pull request. Looked good.

I will work on getting a new build and create a new release after I am off of work for the day.
